run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - errorlint
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - noctx

linters-settings:
  goimports:
    local-prefixes: github.com/wisbric/opswatch
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
