version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - noctx

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/wisbric/nightowl

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
